apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-minion
  namespace: kafka
  labels: &labels
    app: kafka-minion
    type: openmetrics
spec:
  replicas: 1
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: /metrics
    spec:
      containers:
      - name: kafka-minion
        image: quay.io/google-cloud-tools/kafka-minion:v0.1.2@sha256:756faaa4b7ce39b9f7d76c0cf9570ab0cf6a9c921e407acd0f12ca933abe202e
        env:
        - name: TELEMETRY_HOST
          value: 0.0.0.0
        - name: TELEMETRY_PORT
          value: "8080"
        - name: EXPORTER_IGNORE_SYSTEM_TOPICS
          value: "true"
        - name: EXPORTER_METRICS_PREFIX
          value: kafka_minion
        - name: LOG_LEVEL
          value: info
        - name: KAFKA_BROKERS
          value: kafka-0.broker:9092, kafka-1.broker:9092, kafka-2.broker:9092
        - name: KAFKA_CONSUMER_OFFSETS_TOPIC_NAME
          value: __consumer_offsets
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          failureThreshold: 1
          httpGet:
            port: http
            path: /metrics
        livenessProbe:
          failureThreshold: 3
          httpGet:
            port: http
            path: /metrics
