bases:
# With prometheus-operator only you must add your own Prometheus and Alertmanager resources
#- github.com/coreos/prometheus-operator?ref=de9a6e1
- github.com/coreos/kube-prometheus?ref=3a64636
- ../../consumers-prometheus
# The ../../prometheus base must be edited to point to the chosen kafka base
#- ../../prometheus
resources:
- k8s-kafka-rbac.yaml
# with base ../../prometheus
- k8s-kafka-servicemonitor.yaml
# with base ../../consumers-prometheus
- k8s-minion-servicemonitor.yaml
patchesStrategicMerge:
- prometheus-k8s-scale-1.yaml
- prometheus-k8s-2.9.2.yaml
- alertmanager-main-scale-1.yaml
- prometheus-k8s-nodeport.yaml
- additional-scrape-configs.yaml
secretGenerator:
- name: additional-scrape-configs
  namespace: monitoring
  #kvSources:
  #- name: pods-discovery-by-prometheus-io-annotations.yaml
    #pluginType: builtin
    #args:
    #- scrape-configs/pods-discovery-by-prometheus-io-annotations.yaml
  files:
  - scrape-configs/pods-discovery-by-prometheus-io-annotations.yaml
