apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka
spec:
  replicas: 1
  template:
    spec:
      volumes:
      - name: data
        emptyDir: {}
  volumeClaimTemplates: []
